version: '2.4'
services:
  jenkins:
    build: jenkins_controller
    container_name: jenkins
    ports:
      - "8880:8080"
      - "50000:50000"
    restart: always
    volumes:
      - ./jenkins_controller/jenkins.yaml:/usr/share/jenkins/ref/jenkins.yaml



  jenkins_agent:
    depends_on:
      - jenkins
    build: jenkins_agent
    container_name: jenkins_agent
    ports:
      - "2222:22"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  sonarqube:
    depends_on:
      - jenkins
    image: sonarqube:10.2.1-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    restart: always
